version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      NODE_ENV: development
      MONGO_URI: mongodb://localhost/payeverdb
    depends_on:
      - mongo
      - rabbitmq
  mongo:
    image: mongo:4.4
    restart: always
    environment:
      MONGO_INITDB_DATABASE: 'payeverdb'
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
  rabbitmq:
    image: rabbitmq:3.8
    restart: always
    env_file:
      - .env
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - /var/lib/rabbitmq

volumes:
  mongo-data:

